version: '3'

services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./scripts/load_data.sql:/docker-entrypoint-initdb.d/load_data.sql
    ports:
      - 5432:5432

