version: '3'
services:
  timescale:
    container_name: timescale
    image: timescale/timescaledb:latest-pg10
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
    - ./db/scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    - ./db/scripts/load_data.sql:/docker-entrypoint-initdb.d/load_data.sql
    -  db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v2.35.1-ce.cli-migrations-v2
    ports:
    - "8080:8080"
    depends_on:
    - "timescale"
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@timescale:5432/postgres
      HASURA_GRAPHQL_ACCESS_KEY: mylongsecretkey
    command:
      - graphql-engine
      - serve
      - --enable-console
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
volumes:
  db_data:
